version: "3.9"

services:
  php:
    build:
      args:
        user: 1000
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sal-plus-php
    container_name: sal-plus-php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db

  nginx:
    container_name: sal-plus-server
    image: nginx:alpine
    ports:
      - 8989:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/

  db:
    image: mysql:5
    container_name: sal-plus-db
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/db/data:/var/lib/mysql
